name: JAM test

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    services:
      postgres_main:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        #   POSTGRES_DB: imdb_apollo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    strategy:
      matrix:
        python-version: ["3.10.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
           python-version: ${{ matrix.python-version }}


      - name: Setup and start virtual environment
        run: | 
            python3 -m venv venv 
            source venv/bin/activate
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Run tests
        env:
          DEBUG: "0"
          DB_HOST: localhost
          DB_DATABASE: postgres
          DB_PORT: 5432
        run: |
          cd backend
          python3 manage.py test